spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://efubtoy-database.cpvsyta1flas.ap-northeast-2.rds.amazonaws.com:3306/efubtoy?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: efubtoyadmin
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true